# Generated by Django 4.0.1 on 2022-10-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-type-images')),
                ('percentage_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('fixed_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('commission_applicable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcategory')),
            ],
        ),
    ]
