# Generated by Django 4.0.1 on 2022-10-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_profile_verification_code'),
        ('ecommerce', '0005_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=200)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updates_on', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartbill',
            name='shipper',
        ),
        migrations.AddField(
            model_name='cartbill',
            name='shipper_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('pending', 'Pending')], default='confirmed', max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('packed_on', models.DateTimeField(blank=True, null=True)),
                ('shipped_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('payment_on', models.DateTimeField(blank=True, null=True)),
                ('refunded_on', models.DateTimeField(blank=True, null=True)),
                ('request_for_return', models.BooleanField(default=False)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('product_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productdetail')),
            ],
            options={
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['price', 'quantity', 'discount', 'total', 'status', 'delivery_date', 'created_on', 'updated_on', 'cancelled_on', 'packed_on', 'shipped_on', 'delivered_on', 'returned_on', 'payment_on', 'refunded_on', 'request_for_return'], name='ecommerce_o_price_7a94a5_idx'),
        ),
    ]
