# Generated by Django 4.0.1 on 2022-10-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.brand'),
        ),
    ]
