# Generated by Django 4.0.1 on 2022-11-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_productdetail_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
