# Generated by Django 4.0.1 on 2022-11-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_returnreason_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproductimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='returns'),
        ),
    ]
