# Generated by Django 4.0.1 on 2022-11-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_alter_sellerdetail_business_type_and_more'),
        ('ecommerce', '0016_returnproductimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipper_name',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='company_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='company_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='packed', max_length=50)),
                ('notified_for', models.CharField(blank=True, max_length=200, null=True)),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_settled', models.BooleanField(blank=True, default=False, null=True)),
                ('shipper_settled_date', models.DateTimeField(blank=True, null=True)),
                ('merchant_settled', models.BooleanField(blank=True, default=False, null=True)),
                ('merchant_settled_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cart')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.seller')),
            ],
            options={
                'verbose_name_plural': 'Order Entries',
            },
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['item_total', 'management_fee', 'delivery_fee', 'total', 'status', 'order_no', 'tracking_id', 'merchant_settled', 'created_on', 'updated_on'], name='ecommerce_o_item_to_b12b29_idx'),
        ),
    ]
