# Generated by Django 4.0.1 on 2022-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_remove_order_shipper_name_cartproduct_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='waybill_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
