# Generated by Django 4.0.1 on 2022-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_orderproduct_waybill_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartBill',
        ),
    ]
