# Generated by Django 4.0.1 on 2022-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_delete_cartbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproductimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='returns'),
        ),
    ]
