# Generated by Django 4.0.1 on 2022-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_productcategory_image'),
        ('ecommerce', '0021_alter_returnedproduct_reason'),
    ]

    operations = [
    ]
