# Generated by Django 4.0.1 on 2022-11-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_merge_20221126_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Describe the product', null=True),
        ),
    ]
