# Generated by Django 4.0.1 on 2022-12-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_remove_productdetail_description_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_town_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_town_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
