# Generated by Django 4.0.1 on 2022-12-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_order_receiver_town_id_order_sender_town_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_town_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_town_id',
        ),
    ]
