# Generated by Django 4.0.1 on 2023-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_product_approved_by_product_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_viewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
