# Generated by Django 4.0.1 on 2023-01-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_product_last_viewed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnreason',
            name='slug',
        ),
    ]
