# Generated by Django 4.0.1 on 2023-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_promo_product_type_promo_product_type_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='position',
            field=models.CharField(choices=[('header_banner', 'Header Banner'), ('footer_banner', 'Footer Banner'), ('big_banner', 'Big Banner'), ('medium_banner', 'Medium Banner'), ('small_banner', 'Small Banner'), ('big_deal', 'Big Deal'), ('medium_deal', 'Medium Deal'), ('small_deal', 'Small Deal')], default='small_banner', max_length=300),
        ),
    ]
