# Generated by Django 4.0.1 on 2023-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='position',
            field=models.CharField(blank=True, choices=[('header_banner', 'Header Banner'), ('footer_banner', 'Footer Banner'), ('big_banner', 'Big Banner'), ('medium_banner', 'Medium Banner'), ('small_banner', 'Small Banner'), ('big_deal', 'Big Deal'), ('medium_deal', 'Medium Deal'), ('small_deal', 'Small Deal')], max_length=300, null=True),
        ),
    ]
