# Generated by Django 4.0.1 on 2023-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_product_slug_promo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
