# Generated by Django 4.0.1 on 2023-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_productcategory_slug_producttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='booked',
            field=models.BooleanField(default=True),
        ),
    ]
