# Generated by Django 4.0.1 on 2022-11-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_update',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
