# Generated by Django 4.0.1 on 2022-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_role_can_create_remove_role_can_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='admin_type',
            field=models.CharField(choices=[('reviewer', 'Reviewer'), ('authorizer', 'Authorizer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='reviewer', max_length=100),
        ),
    ]
