# Generated by Django 4.0.1 on 2022-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
    ]
