# Generated by Django 4.0.1 on 2022-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_seller_city_seller_state_seller_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
