# Generated by Django 4.0.1 on 2022-10-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_seller_latitude_seller_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_state', models.CharField(blank=True, max_length=100, null=True)),
                ('business_city', models.CharField(blank=True, max_length=100, null=True)),
                ('business_drop_off_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('unregistered-individual-business', 'Unregistered Individual Business'), ('registered-individual-business', 'Registered Individual Business'), ('limited-liability-company', 'Individual')], max_length=100, null=True)),
                ('market_size', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_outlets', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_price_range', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='seller-verification')),
                ('id_card_verified', models.BooleanField(default=False)),
                ('cac_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cac_verified', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchant.seller')),
            ],
        ),
        migrations.DeleteModel(
            name='SellerVerification',
        ),
    ]
