# Generated by Django 4.0.1 on 2022-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_orderproduct_status'),
        ('merchant', '0006_director_sellerdetail_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetail',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='ecommerce.ProductCategory'),
        ),
    ]
