# Generated by Django 4.0.1 on 2022-10-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_sellerdetail_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdetail',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='sellerdetail',
            name='product_category',
        ),
    ]
