# Generated by Django 4.0.1 on 2022-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_remove_sellerdetail_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetail',
            name='company_type',
            field=models.CharField(blank=True, choices=[('sole-proprietorship', 'SOLE-PROPRIETORSHIP'), ('partnership', 'Partnership / Joint Venture')], max_length=100, null=True),
        ),
    ]
