# Generated by Django 4.0.1 on 2022-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0014_remove_seller_umap_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='biller_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='feel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='fep_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('rate', 'Rate')], default='flat', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approve', 'Approve')], default='pending', max_length=20, null=True),
        ),
    ]
