# Generated by Django 4.0.1 on 2022-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0015_bankaccount_bank_code_seller_biller_code_seller_feel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
