# Generated by Django 4.0.1 on 2022-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0016_seller_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='town_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
