# Generated by Django 4.0.1 on 2023-02-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0019_alter_seller_latitude_alter_seller_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantbanner',
            name='banner_size',
        ),
    ]
