# Generated by Django 4.0.1 on 2023-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0020_remove_merchantbanner_banner_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk-upload')),
                ('used', models.BooleanField(default=False)),
                ('errors', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approve', 'Approve'), ('checked', 'Checked')], default='pending', max_length=20, null=True),
        ),
    ]
