# Generated by Django 4.0.1 on 2023-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0021_bulkuploadfile_alter_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadfile',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
