# Generated by Django 4.0.1 on 2022-09-26 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.SlugField(max_length=20)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='If token was sent successfully')),
                ('is_used', models.BooleanField(default=False, help_text='If token has been used')),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 13, 54, 54, 917742, tzinfo=utc), help_text='Expires after 5 minutes')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=50, null=True)),
                ('card_from', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=50, null=True)),
                ('card_type', models.CharField(max_length=50, null=True)),
                ('bin', models.CharField(max_length=300, null=True)),
                ('last4', models.CharField(max_length=50, null=True)),
                ('exp_month', models.CharField(max_length=2, null=True)),
                ('exp_year', models.CharField(max_length=4, null=True)),
                ('signature', models.CharField(max_length=200, null=True)),
                ('authorization_code', models.CharField(max_length=200, null=True)),
                ('payload', models.TextField(null=True)),
                ('default', models.BooleanField(default=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
