# Generated by Django 4.0.1 on 2022-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_code_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
