# Generated by Django 4.0.1 on 2022-11-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_has_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
