# Generated by Django 4.0.1 on 2022-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_pay_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_pin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
