# Generated by Django 4.0.1 on 2022-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_billing_id_profile_billing_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='town_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
