# Generated by Django 4.0.1 on 2022-12-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_address_town_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_verified',
        ),
    ]
