# Generated by Django 4.0.1 on 2023-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent_viewed_products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
