# Generated by Django 4.0.1 on 2023-01-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_recent_viewed_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPasswordOTP',
        ),
    ]
