# Generated by Django 4.0.1 on 2023-01-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_delete_forgotpasswordotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
