# Generated by Django 4.0.1 on 2023-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_on_sale'),
        ('account', '0018_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='store.Store'),
        ),
    ]
