# Generated by Django 4.0.1 on 2022-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
