# Generated by Django 4.0.1 on 2023-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
