# Generated by Django 4.0.1 on 2022-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_remove_seller_city_remove_seller_country_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
