# Generated by Django 4.0.1 on 2022-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_created_on_transaction_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('-', '-------'), ('card', 'Card'), ('wallet', 'Wallet'), ('transfer', 'Transfer'), ('pay_attitude', 'Pay Attitude')], default='-', max_length=100),
        ),
    ]
